// Auto-generated by scripts/generate-line-slots.js
// Do not edit manually.

export type NormalizedLineSlot = {
  x: number;
  y: number;
  width: number;
  height: number;
  hasLabel: boolean;
  continuationGroup: number;
  inputKind?: 'line' | 'block';
};

export const LINE_SLOTS = {
  "diary_interior_brown": {
    "1": [
      {
        "x": 0.27498,
        "y": 0.33007,
        "width": 0.45482,
        "height": 0.03919,
        "hasLabel": false,
        "continuationGroup": 1
      },
      {
        "x": 0.28351,
        "y": 0.36926,
        "width": 0.45342,
        "height": 0.03919,
        "hasLabel": false,
        "continuationGroup": 2
      }
    ],
    "2": [],
    "3": [],
    "4": [],
    "5": [],
    "6": [
      {
        "x": 0.33978,
        "y": 0.28728,
        "width": 0.58008,
        "height": 0.05254,
        "hasLabel": false,
        "continuationGroup": 1
      },
      {
        "x": 0.37528,
        "y": 0.33982,
        "width": 0.54393,
        "height": 0.05122,
        "hasLabel": false,
        "continuationGroup": 2
      },
      {
        "x": 0.4205,
        "y": 0.38971,
        "width": 0.49964,
        "height": 0.04685,
        "hasLabel": false,
        "continuationGroup": 3
      },
      {
        "x": 0.40983,
        "y": 0.43351,
        "width": 0.5114,
        "height": 0.07581,
        "hasLabel": false,
        "continuationGroup": 4
      },
      {
        "x": 0.51374,
        "y": 0.54133,
        "width": 0.40548,
        "height": 0.07885,
        "hasLabel": false,
        "continuationGroup": 5
      },
      {
        "x": 0.43773,
        "y": 0.59122,
        "width": 0.4824,
        "height": 0.04887,
        "hasLabel": false,
        "continuationGroup": 6
      },
      {
        "x": 0.39823,
        "y": 0.63906,
        "width": 0.5219,
        "height": 0.04769,
        "hasLabel": false,
        "continuationGroup": 7
      },
      {
        "x": 0.33764,
        "y": 0.68659,
        "width": 0.5825,
        "height": 0.04984,
        "hasLabel": false,
        "continuationGroup": 8
      },
      {
        "x": 0.29059,
        "y": 0.73875,
        "width": 0.62954,
        "height": 0.05216,
        "hasLabel": false,
        "continuationGroup": 9
      }
    ],
    "7": [
      {
        "x": 0.32602,
        "y": 0.30289,
        "width": 0.5941,
        "height": 0.04272,
        "hasLabel": false,
        "continuationGroup": 1
      },
      {
        "x": 0.33023,
        "y": 0.34561,
        "width": 0.58886,
        "height": 0.04314,
        "hasLabel": false,
        "continuationGroup": 2
      },
      {
        "x": 0.28116,
        "y": 0.38916,
        "width": 0.64383,
        "height": 0.04293,
        "hasLabel": false,
        "continuationGroup": 3
      },
      {
        "x": 0.23001,
        "y": 0.43148,
        "width": 0.68894,
        "height": 0.04269,
        "hasLabel": false,
        "continuationGroup": 4
      },
      {
        "x": 0.34384,
        "y": 0.47454,
        "width": 0.57528,
        "height": 0.04346,
        "hasLabel": false,
        "continuationGroup": 5
      },
      {
        "x": 0.38773,
        "y": 0.51839,
        "width": 0.53122,
        "height": 0.04311,
        "hasLabel": false,
        "continuationGroup": 6
      },
      {
        "x": 0.32167,
        "y": 0.56076,
        "width": 0.59728,
        "height": 0.04257,
        "hasLabel": false,
        "continuationGroup": 7
      },
      {
        "x": 0.39812,
        "y": 0.60353,
        "width": 0.52083,
        "height": 0.04182,
        "hasLabel": false,
        "continuationGroup": 8
      },
      {
        "x": 0.16888,
        "y": 0.64439,
        "width": 0.75007,
        "height": 0.04176,
        "hasLabel": false,
        "continuationGroup": 9
      },
      {
        "x": 0.37095,
        "y": 0.68706,
        "width": 0.54767,
        "height": 0.04292,
        "hasLabel": false,
        "continuationGroup": 10
      },
      {
        "x": 0.33492,
        "y": 0.73023,
        "width": 0.58371,
        "height": 0.04364,
        "hasLabel": false,
        "continuationGroup": 11
      },
      {
        "x": 0.53894,
        "y": 0.77433,
        "width": 0.38044,
        "height": 0.04411,
        "hasLabel": false,
        "continuationGroup": 12
      }
    ],
    "8": [
      {
        "x": 0.32602,
        "y": 0.30289,
        "width": 0.5941,
        "height": 0.04272,
        "hasLabel": false,
        "continuationGroup": 1
      },
      {
        "x": 0.33023,
        "y": 0.34561,
        "width": 0.58886,
        "height": 0.04314,
        "hasLabel": false,
        "continuationGroup": 2
      },
      {
        "x": 0.28116,
        "y": 0.38916,
        "width": 0.64383,
        "height": 0.04293,
        "hasLabel": false,
        "continuationGroup": 3
      },
      {
        "x": 0.23001,
        "y": 0.43148,
        "width": 0.68894,
        "height": 0.04269,
        "hasLabel": false,
        "continuationGroup": 4
      },
      {
        "x": 0.34384,
        "y": 0.47454,
        "width": 0.57528,
        "height": 0.04346,
        "hasLabel": false,
        "continuationGroup": 5
      },
      {
        "x": 0.38773,
        "y": 0.51839,
        "width": 0.53122,
        "height": 0.04311,
        "hasLabel": false,
        "continuationGroup": 6
      },
      {
        "x": 0.32167,
        "y": 0.56076,
        "width": 0.59728,
        "height": 0.04257,
        "hasLabel": false,
        "continuationGroup": 7
      },
      {
        "x": 0.39812,
        "y": 0.60353,
        "width": 0.52083,
        "height": 0.04182,
        "hasLabel": false,
        "continuationGroup": 8
      },
      {
        "x": 0.16888,
        "y": 0.64439,
        "width": 0.75007,
        "height": 0.04176,
        "hasLabel": false,
        "continuationGroup": 9
      },
      {
        "x": 0.37095,
        "y": 0.68706,
        "width": 0.54767,
        "height": 0.04292,
        "hasLabel": false,
        "continuationGroup": 10
      },
      {
        "x": 0.33492,
        "y": 0.73023,
        "width": 0.58371,
        "height": 0.04364,
        "hasLabel": false,
        "continuationGroup": 11
      },
      {
        "x": 0.53894,
        "y": 0.77433,
        "width": 0.38044,
        "height": 0.04411,
        "hasLabel": false,
        "continuationGroup": 12
      }
    ],
    "9": [
      {
        "x": 0.48089,
        "y": 0.53107,
        "width": 0.20052,
        "height": 0.028,
        "hasLabel": false,
        "continuationGroup": 1
      }
    ],
    "10": [],
    "11": [
      {
        "x": 0.32543,
        "y": 0.30194,
        "width": 0.5941,
        "height": 0.04272,
        "hasLabel": false,
        "continuationGroup": 1
      },
      {
        "x": 0.32963,
        "y": 0.34466,
        "width": 0.58886,
        "height": 0.04314,
        "hasLabel": false,
        "continuationGroup": 2
      },
      {
        "x": 0.28056,
        "y": 0.38821,
        "width": 0.64383,
        "height": 0.04293,
        "hasLabel": false,
        "continuationGroup": 3
      },
      {
        "x": 0.22942,
        "y": 0.43052,
        "width": 0.68894,
        "height": 0.04269,
        "hasLabel": false,
        "continuationGroup": 4
      },
      {
        "x": 0.34324,
        "y": 0.47359,
        "width": 0.57528,
        "height": 0.04346,
        "hasLabel": false,
        "continuationGroup": 5
      },
      {
        "x": 0.38713,
        "y": 0.51744,
        "width": 0.53122,
        "height": 0.04311,
        "hasLabel": false,
        "continuationGroup": 6
      },
      {
        "x": 0.32107,
        "y": 0.55981,
        "width": 0.59728,
        "height": 0.04257,
        "hasLabel": false,
        "continuationGroup": 7
      },
      {
        "x": 0.39752,
        "y": 0.60258,
        "width": 0.52083,
        "height": 0.04182,
        "hasLabel": false,
        "continuationGroup": 8
      },
      {
        "x": 0.16828,
        "y": 0.64344,
        "width": 0.75007,
        "height": 0.04176,
        "hasLabel": false,
        "continuationGroup": 9
      },
      {
        "x": 0.37035,
        "y": 0.68611,
        "width": 0.54767,
        "height": 0.04292,
        "hasLabel": false,
        "continuationGroup": 10
      },
      {
        "x": 0.33432,
        "y": 0.72928,
        "width": 0.58371,
        "height": 0.04364,
        "hasLabel": false,
        "continuationGroup": 11
      },
      {
        "x": 0.53834,
        "y": 0.77338,
        "width": 0.38044,
        "height": 0.04411,
        "hasLabel": false,
        "continuationGroup": 12
      }
    ],
    "12": [
      {
        "x": 0.32471,
        "y": 0.30194,
        "width": 0.5941,
        "height": 0.04272,
        "hasLabel": false,
        "continuationGroup": 1
      },
      {
        "x": 0.32892,
        "y": 0.34466,
        "width": 0.58886,
        "height": 0.04314,
        "hasLabel": false,
        "continuationGroup": 2
      },
      {
        "x": 0.27984,
        "y": 0.38821,
        "width": 0.64383,
        "height": 0.04293,
        "hasLabel": false,
        "continuationGroup": 3
      },
      {
        "x": 0.2287,
        "y": 0.43052,
        "width": 0.68894,
        "height": 0.04269,
        "hasLabel": false,
        "continuationGroup": 4
      },
      {
        "x": 0.34252,
        "y": 0.47359,
        "width": 0.57528,
        "height": 0.04346,
        "hasLabel": false,
        "continuationGroup": 5
      },
      {
        "x": 0.38641,
        "y": 0.51744,
        "width": 0.53122,
        "height": 0.04311,
        "hasLabel": false,
        "continuationGroup": 6
      },
      {
        "x": 0.32035,
        "y": 0.55981,
        "width": 0.59728,
        "height": 0.04257,
        "hasLabel": false,
        "continuationGroup": 7
      },
      {
        "x": 0.3968,
        "y": 0.60258,
        "width": 0.52083,
        "height": 0.04182,
        "hasLabel": false,
        "continuationGroup": 8
      },
      {
        "x": 0.16756,
        "y": 0.64344,
        "width": 0.75007,
        "height": 0.04176,
        "hasLabel": false,
        "continuationGroup": 9
      },
      {
        "x": 0.36963,
        "y": 0.68611,
        "width": 0.54767,
        "height": 0.04292,
        "hasLabel": false,
        "continuationGroup": 10
      },
      {
        "x": 0.3336,
        "y": 0.72928,
        "width": 0.58371,
        "height": 0.04364,
        "hasLabel": false,
        "continuationGroup": 11
      },
      {
        "x": 0.53762,
        "y": 0.77338,
        "width": 0.38044,
        "height": 0.04411,
        "hasLabel": false,
        "continuationGroup": 12
      }
    ],
    "13": [
      {
        "x": 0.30111,
        "y": 0.26932,
        "width": 0.6167,
        "height": 0.12,
        "hasLabel": false,
        "continuationGroup": 1
      },
      {
        "x": 0.3816,
        "y": 0.42813,
        "width": 0.53773,
        "height": 0.08,
        "hasLabel": false,
        "continuationGroup": 2
      },
      {
        "x": 0.42872,
        "y": 0.46528,
        "width": 0.49061,
        "height": 0.03797,
        "hasLabel": false,
        "continuationGroup": 3
      },
      {
        "x": 0.31904,
        "y": 0.50407,
        "width": 0.60029,
        "height": 0.03745,
        "hasLabel": false,
        "continuationGroup": 4
      },
      {
        "x": 0.42773,
        "y": 0.54018,
        "width": 0.4916,
        "height": 0.0366,
        "hasLabel": false,
        "continuationGroup": 5
      },
      {
        "x": 0.31656,
        "y": 0.57727,
        "width": 0.59813,
        "height": 0.03689,
        "hasLabel": false,
        "continuationGroup": 6
      },
      {
        "x": 0.40894,
        "y": 0.61397,
        "width": 0.50786,
        "height": 0.03854,
        "hasLabel": false,
        "continuationGroup": 7
      },
      {
        "x": 0.39454,
        "y": 0.65436,
        "width": 0.52241,
        "height": 0.03835,
        "hasLabel": false,
        "continuationGroup": 8
      },
      {
        "x": 0.42385,
        "y": 0.69067,
        "width": 0.4931,
        "height": 0.03631,
        "hasLabel": false,
        "continuationGroup": 9
      }
    ],
    "14": [],
    "15": [
      {
        "x": 0.1655,
        "y": 0.59806,
        "width": 0.32006,
        "height": 0.028,
        "hasLabel": false,
        "continuationGroup": 1
      }
    ],
    "16": [
      {
        "x": 0.33511,
        "y": 0.60996,
        "width": 0.47134,
        "height": 0.028,
        "hasLabel": false,
        "continuationGroup": 1
      }
    ],
    "17": [
      {
        "x": 0.45602,
        "y": 0.39682,
        "width": 0.46026,
        "height": 0.05283,
        "hasLabel": false,
        "continuationGroup": 1
      },
      {
        "x": 0.37685,
        "y": 0.44965,
        "width": 0.53909,
        "height": 0.05283,
        "hasLabel": false,
        "continuationGroup": 2
      }
    ],
    "18": [],
    "19": [
      {
        "x": 0.52299,
        "y": 0.62553,
        "width": 0.14215,
        "height": 0.028,
        "hasLabel": false,
        "continuationGroup": 1
      }
    ],
    "20": [
      {
        "x": 0.32289,
        "y": 0.60996,
        "width": 0.47134,
        "height": 0.028,
        "hasLabel": false,
        "continuationGroup": 1
      }
    ],
    "21": [
      {
        "x": 0.52109,
        "y": 0.32039,
        "width": 0.39985,
        "height": 0.07632,
        "hasLabel": false,
        "continuationGroup": 1
      },
      {
        "x": 0.38845,
        "y": 0.39671,
        "width": 0.53249,
        "height": 0.05621,
        "hasLabel": false,
        "continuationGroup": 2
      },
      {
        "x": 0.46439,
        "y": 0.43281,
        "width": 0.45655,
        "height": 0.08,
        "hasLabel": false,
        "continuationGroup": 3
      },
      {
        "x": 0.58349,
        "y": 0.63646,
        "width": 0.33608,
        "height": 0.08,
        "hasLabel": false,
        "continuationGroup": 4
      },
      {
        "x": 0.58175,
        "y": 0.6734,
        "width": 0.33781,
        "height": 0.03694,
        "hasLabel": false,
        "continuationGroup": 5
      }
    ],
    "22": [],
    "23": [
      {
        "x": 0.33511,
        "y": 0.60996,
        "width": 0.47134,
        "height": 0.028,
        "hasLabel": false,
        "continuationGroup": 1
      }
    ],
    "24": [
      {
        "x": 0.47261,
        "y": 0.29087,
        "width": 0.44372,
        "height": 0.0441,
        "hasLabel": false,
        "continuationGroup": 1
      },
      {
        "x": 0.3673,
        "y": 0.33497,
        "width": 0.54903,
        "height": 0.04557,
        "hasLabel": false,
        "continuationGroup": 2
      },
      {
        "x": 0.49954,
        "y": 0.38201,
        "width": 0.41679,
        "height": 0.04532,
        "hasLabel": false,
        "continuationGroup": 3
      },
      {
        "x": 0.51239,
        "y": 0.42561,
        "width": 0.40394,
        "height": 0.04483,
        "hasLabel": false,
        "continuationGroup": 4
      },
      {
        "x": 0.59408,
        "y": 0.47167,
        "width": 0.32225,
        "height": 0.04435,
        "hasLabel": false,
        "continuationGroup": 5
      },
      {
        "x": 0.5646,
        "y": 0.5143,
        "width": 0.35173,
        "height": 0.08,
        "hasLabel": false,
        "continuationGroup": 6
      },
      {
        "x": 0.16003,
        "y": 0.64438,
        "width": 0.74528,
        "height": 0.08,
        "hasLabel": false,
        "continuationGroup": 7
      },
      {
        "x": 0.16003,
        "y": 0.70575,
        "width": 0.74528,
        "height": 0.06155,
        "hasLabel": false,
        "continuationGroup": 8
      },
      {
        "x": 0.16003,
        "y": 0.76749,
        "width": 0.74528,
        "height": 0.06174,
        "hasLabel": false,
        "continuationGroup": 9
      }
    ],
    "25": [
      {
        "x": 0.33511,
        "y": 0.60996,
        "width": 0.47134,
        "height": 0.028,
        "hasLabel": false,
        "continuationGroup": 1
      }
    ],
    "26": [
      {
        "x": 0.56468,
        "y": 0.50128,
        "width": 0.36451,
        "height": 0.07592,
        "hasLabel": false,
        "continuationGroup": 1
      },
      {
        "x": 0.56887,
        "y": 0.5772,
        "width": 0.36032,
        "height": 0.08,
        "hasLabel": false,
        "continuationGroup": 2
      },
      {
        "x": 0.51889,
        "y": 0.76104,
        "width": 0.4103,
        "height": 0.12,
        "hasLabel": false,
        "continuationGroup": 3
      }
    ],
    "27": [],
    "28": [
      {
        "x": 0.32147,
        "y": 0.60996,
        "width": 0.47134,
        "height": 0.028,
        "hasLabel": false,
        "continuationGroup": 1
      }
    ],
    "29": [],
    "30": [
      {
        "x": 0.17389,
        "y": 0.32966,
        "width": 0.65556,
        "height": 0.08764,
        "hasLabel": false,
        "continuationGroup": 1
      },
      {
        "x": 0.44722,
        "y": 0.41729,
        "width": 0.10942,
        "height": 0.08,
        "hasLabel": false,
        "continuationGroup": 2
      },
      {
        "x": 0.45257,
        "y": 0.51679,
        "width": 0.4215,
        "height": 0.08,
        "hasLabel": false,
        "continuationGroup": 3
      },
      {
        "x": 0.17389,
        "y": 0.65034,
        "width": 0.65556,
        "height": 0.12,
        "hasLabel": false,
        "continuationGroup": 4
      }
    ],
    "31": [
      {
        "x": 0.60665,
        "y": 0.31784,
        "width": 0.33802,
        "height": 0.0979,
        "hasLabel": false,
        "continuationGroup": 1
      },
      {
        "x": 0.53075,
        "y": 0.41574,
        "width": 0.41392,
        "height": 0.08,
        "hasLabel": false,
        "continuationGroup": 2
      },
      {
        "x": 0.38715,
        "y": 0.48095,
        "width": 0.55751,
        "height": 0.0671,
        "hasLabel": false,
        "continuationGroup": 3
      },
      {
        "x": 0.6125,
        "y": 0.54995,
        "width": 0.33217,
        "height": 0.06138,
        "hasLabel": false,
        "continuationGroup": 4
      },
      {
        "x": 0.20487,
        "y": 0.6037,
        "width": 0.3461,
        "height": 0.07569,
        "hasLabel": false,
        "continuationGroup": 5
      },
      {
        "x": 0.54983,
        "y": 0.70132,
        "width": 0.39484,
        "height": 0.07935,
        "hasLabel": false,
        "continuationGroup": 6
      },
      {
        "x": 0.17341,
        "y": 0.76241,
        "width": 0.64275,
        "height": 0.06109,
        "hasLabel": false,
        "continuationGroup": 7
      }
    ],
    "32": [
      {
        "x": 0.53252,
        "y": 0.34901,
        "width": 0.22483,
        "height": 0.02955,
        "hasLabel": false,
        "continuationGroup": 1
      },
      {
        "x": 0.34637,
        "y": 0.37856,
        "width": 0.32924,
        "height": 0.05924,
        "hasLabel": false,
        "continuationGroup": 2
      },
      {
        "x": 0.21644,
        "y": 0.4675,
        "width": 0.52407,
        "height": 0.08,
        "hasLabel": false,
        "continuationGroup": 3
      },
      {
        "x": 0.33826,
        "y": 0.71473,
        "width": 0.15956,
        "height": 0.08,
        "hasLabel": false,
        "continuationGroup": 4
      },
      {
        "x": 0.53866,
        "y": 0.74601,
        "width": 0.27049,
        "height": 0.03128,
        "hasLabel": false,
        "continuationGroup": 5
      }
    ],
    "33": [
      {
        "x": 0.33511,
        "y": 0.60996,
        "width": 0.47134,
        "height": 0.028,
        "hasLabel": false,
        "continuationGroup": 1
      }
    ],
    "34": [],
    "35": [],
    "36": [],
    "37": [
      {
        "x": 0.30083,
        "y": 0.30449,
        "width": 0.6458,
        "height": 0.0454,
        "hasLabel": false,
        "continuationGroup": 1
      },
      {
        "x": 0.35132,
        "y": 0.34989,
        "width": 0.59531,
        "height": 0.0454,
        "hasLabel": false,
        "continuationGroup": 2
      },
      {
        "x": 0.32574,
        "y": 0.39529,
        "width": 0.61792,
        "height": 0.0454,
        "hasLabel": false,
        "continuationGroup": 3
      }
    ],
    "38": [
      {
        "x": 0.56708,
        "y": 0.3282,
        "width": 0.30349,
        "height": 0.05755,
        "hasLabel": false,
        "continuationGroup": 1
      },
      {
        "x": 0.53955,
        "y": 0.38574,
        "width": 0.33028,
        "height": 0.08,
        "hasLabel": false,
        "continuationGroup": 2
      },
      {
        "x": 0.37009,
        "y": 0.59646,
        "width": 0.49974,
        "height": 0.12,
        "hasLabel": false,
        "continuationGroup": 3
      }
    ],
    "39": [
      {
        "x": 0.29147,
        "y": 0.27759,
        "width": 0.65516,
        "height": 0.0365,
        "hasLabel": false,
        "continuationGroup": 1
      },
      {
        "x": 0.28343,
        "y": 0.3141,
        "width": 0.6632,
        "height": 0.03937,
        "hasLabel": false,
        "continuationGroup": 2
      },
      {
        "x": 0.35831,
        "y": 0.35634,
        "width": 0.58832,
        "height": 0.0424,
        "hasLabel": false,
        "continuationGroup": 3
      },
      {
        "x": 0.28821,
        "y": 0.3989,
        "width": 0.65842,
        "height": 0.04222,
        "hasLabel": false,
        "continuationGroup": 4
      },
      {
        "x": 0.31137,
        "y": 0.44078,
        "width": 0.63526,
        "height": 0.04483,
        "hasLabel": false,
        "continuationGroup": 5
      },
      {
        "x": 0.34055,
        "y": 0.48855,
        "width": 0.60608,
        "height": 0.06595,
        "hasLabel": false,
        "continuationGroup": 6
      },
      {
        "x": 0.25041,
        "y": 0.57268,
        "width": 0.69622,
        "height": 0.06289,
        "hasLabel": false,
        "continuationGroup": 7
      },
      {
        "x": 0.29292,
        "y": 0.61432,
        "width": 0.65371,
        "height": 0.04125,
        "hasLabel": false,
        "continuationGroup": 8
      },
      {
        "x": 0.35351,
        "y": 0.65519,
        "width": 0.59312,
        "height": 0.04513,
        "hasLabel": false,
        "continuationGroup": 9
      },
      {
        "x": 0.28164,
        "y": 0.70459,
        "width": 0.66499,
        "height": 0.04752,
        "hasLabel": false,
        "continuationGroup": 10
      },
      {
        "x": 0.29055,
        "y": 0.75023,
        "width": 0.65608,
        "height": 0.04564,
        "hasLabel": false,
        "continuationGroup": 11
      }
    ],
    "40": [
      {
        "x": 0.27147,
        "y": 0.27759,
        "width": 0.65516,
        "height": 0.0365,
        "hasLabel": false,
        "continuationGroup": 1
      },
      {
        "x": 0.26343,
        "y": 0.3141,
        "width": 0.6632,
        "height": 0.03937,
        "hasLabel": false,
        "continuationGroup": 2
      },
      {
        "x": 0.33831,
        "y": 0.35634,
        "width": 0.58832,
        "height": 0.0424,
        "hasLabel": false,
        "continuationGroup": 3
      },
      {
        "x": 0.26821,
        "y": 0.3989,
        "width": 0.65842,
        "height": 0.04222,
        "hasLabel": false,
        "continuationGroup": 4
      },
      {
        "x": 0.29137,
        "y": 0.44078,
        "width": 0.63526,
        "height": 0.04483,
        "hasLabel": false,
        "continuationGroup": 5
      },
      {
        "x": 0.32055,
        "y": 0.48855,
        "width": 0.60608,
        "height": 0.06595,
        "hasLabel": false,
        "continuationGroup": 6
      },
      {
        "x": 0.23041,
        "y": 0.57268,
        "width": 0.69622,
        "height": 0.06289,
        "hasLabel": false,
        "continuationGroup": 7
      },
      {
        "x": 0.27292,
        "y": 0.61432,
        "width": 0.65371,
        "height": 0.04125,
        "hasLabel": false,
        "continuationGroup": 8
      },
      {
        "x": 0.33351,
        "y": 0.65519,
        "width": 0.59312,
        "height": 0.04513,
        "hasLabel": false,
        "continuationGroup": 9
      },
      {
        "x": 0.26164,
        "y": 0.70459,
        "width": 0.66499,
        "height": 0.04752,
        "hasLabel": false,
        "continuationGroup": 10
      },
      {
        "x": 0.27055,
        "y": 0.75023,
        "width": 0.65608,
        "height": 0.04564,
        "hasLabel": false,
        "continuationGroup": 11
      }
    ],
    "41": [
      {
        "x": 0.29091,
        "y": 0.27759,
        "width": 0.65516,
        "height": 0.0365,
        "hasLabel": false,
        "continuationGroup": 1
      },
      {
        "x": 0.28288,
        "y": 0.3141,
        "width": 0.6632,
        "height": 0.03937,
        "hasLabel": false,
        "continuationGroup": 2
      },
      {
        "x": 0.35775,
        "y": 0.35634,
        "width": 0.58832,
        "height": 0.0424,
        "hasLabel": false,
        "continuationGroup": 3
      },
      {
        "x": 0.28766,
        "y": 0.3989,
        "width": 0.65842,
        "height": 0.04222,
        "hasLabel": false,
        "continuationGroup": 4
      },
      {
        "x": 0.31081,
        "y": 0.44078,
        "width": 0.63526,
        "height": 0.04483,
        "hasLabel": false,
        "continuationGroup": 5
      },
      {
        "x": 0.34,
        "y": 0.48855,
        "width": 0.60608,
        "height": 0.06595,
        "hasLabel": false,
        "continuationGroup": 6
      },
      {
        "x": 0.24985,
        "y": 0.57268,
        "width": 0.69622,
        "height": 0.06289,
        "hasLabel": false,
        "continuationGroup": 7
      },
      {
        "x": 0.29237,
        "y": 0.61432,
        "width": 0.65371,
        "height": 0.04125,
        "hasLabel": false,
        "continuationGroup": 8
      },
      {
        "x": 0.35295,
        "y": 0.65519,
        "width": 0.59312,
        "height": 0.04513,
        "hasLabel": false,
        "continuationGroup": 9
      },
      {
        "x": 0.28108,
        "y": 0.70459,
        "width": 0.66499,
        "height": 0.04752,
        "hasLabel": false,
        "continuationGroup": 10
      },
      {
        "x": 0.29,
        "y": 0.75023,
        "width": 0.65608,
        "height": 0.04564,
        "hasLabel": false,
        "continuationGroup": 11
      }
    ],
    "42": [
      {
        "x": 0.26925,
        "y": 0.27759,
        "width": 0.65516,
        "height": 0.0365,
        "hasLabel": false,
        "continuationGroup": 1
      },
      {
        "x": 0.26121,
        "y": 0.3141,
        "width": 0.6632,
        "height": 0.03937,
        "hasLabel": false,
        "continuationGroup": 2
      },
      {
        "x": 0.33608,
        "y": 0.35634,
        "width": 0.58832,
        "height": 0.0424,
        "hasLabel": false,
        "continuationGroup": 3
      },
      {
        "x": 0.26599,
        "y": 0.3989,
        "width": 0.65842,
        "height": 0.04222,
        "hasLabel": false,
        "continuationGroup": 4
      },
      {
        "x": 0.28915,
        "y": 0.44078,
        "width": 0.63526,
        "height": 0.04483,
        "hasLabel": false,
        "continuationGroup": 5
      },
      {
        "x": 0.31833,
        "y": 0.48855,
        "width": 0.60608,
        "height": 0.06595,
        "hasLabel": false,
        "continuationGroup": 6
      },
      {
        "x": 0.22819,
        "y": 0.57268,
        "width": 0.69622,
        "height": 0.06289,
        "hasLabel": false,
        "continuationGroup": 7
      },
      {
        "x": 0.2707,
        "y": 0.61432,
        "width": 0.65371,
        "height": 0.04125,
        "hasLabel": false,
        "continuationGroup": 8
      },
      {
        "x": 0.33129,
        "y": 0.65519,
        "width": 0.59312,
        "height": 0.04513,
        "hasLabel": false,
        "continuationGroup": 9
      },
      {
        "x": 0.25942,
        "y": 0.70459,
        "width": 0.66499,
        "height": 0.04752,
        "hasLabel": false,
        "continuationGroup": 10
      },
      {
        "x": 0.26833,
        "y": 0.75023,
        "width": 0.65608,
        "height": 0.04564,
        "hasLabel": false,
        "continuationGroup": 11
      }
    ],
    "43": [
      {
        "x": 0.2948,
        "y": 0.27759,
        "width": 0.65516,
        "height": 0.0365,
        "hasLabel": false,
        "continuationGroup": 1
      },
      {
        "x": 0.28677,
        "y": 0.3141,
        "width": 0.6632,
        "height": 0.03937,
        "hasLabel": false,
        "continuationGroup": 2
      },
      {
        "x": 0.36164,
        "y": 0.35634,
        "width": 0.58832,
        "height": 0.0424,
        "hasLabel": false,
        "continuationGroup": 3
      },
      {
        "x": 0.29154,
        "y": 0.3989,
        "width": 0.65842,
        "height": 0.04222,
        "hasLabel": false,
        "continuationGroup": 4
      },
      {
        "x": 0.3147,
        "y": 0.44078,
        "width": 0.63526,
        "height": 0.04483,
        "hasLabel": false,
        "continuationGroup": 5
      },
      {
        "x": 0.34389,
        "y": 0.48855,
        "width": 0.60608,
        "height": 0.06595,
        "hasLabel": false,
        "continuationGroup": 6
      },
      {
        "x": 0.25374,
        "y": 0.57268,
        "width": 0.69622,
        "height": 0.06289,
        "hasLabel": false,
        "continuationGroup": 7
      },
      {
        "x": 0.29625,
        "y": 0.61432,
        "width": 0.65371,
        "height": 0.04125,
        "hasLabel": false,
        "continuationGroup": 8
      },
      {
        "x": 0.35684,
        "y": 0.65519,
        "width": 0.59312,
        "height": 0.04513,
        "hasLabel": false,
        "continuationGroup": 9
      },
      {
        "x": 0.28497,
        "y": 0.70459,
        "width": 0.66499,
        "height": 0.04752,
        "hasLabel": false,
        "continuationGroup": 10
      },
      {
        "x": 0.29388,
        "y": 0.75023,
        "width": 0.65608,
        "height": 0.04564,
        "hasLabel": false,
        "continuationGroup": 11
      }
    ],
    "44": [
      {
        "x": 0.2648,
        "y": 0.27759,
        "width": 0.65516,
        "height": 0.0365,
        "hasLabel": false,
        "continuationGroup": 1
      },
      {
        "x": 0.25677,
        "y": 0.3141,
        "width": 0.6632,
        "height": 0.03937,
        "hasLabel": false,
        "continuationGroup": 2
      },
      {
        "x": 0.33164,
        "y": 0.35634,
        "width": 0.58832,
        "height": 0.0424,
        "hasLabel": false,
        "continuationGroup": 3
      },
      {
        "x": 0.26154,
        "y": 0.3989,
        "width": 0.65842,
        "height": 0.04222,
        "hasLabel": false,
        "continuationGroup": 4
      },
      {
        "x": 0.2847,
        "y": 0.44078,
        "width": 0.63526,
        "height": 0.04483,
        "hasLabel": false,
        "continuationGroup": 5
      },
      {
        "x": 0.31389,
        "y": 0.48855,
        "width": 0.60608,
        "height": 0.06595,
        "hasLabel": false,
        "continuationGroup": 6
      },
      {
        "x": 0.22374,
        "y": 0.57268,
        "width": 0.69622,
        "height": 0.06289,
        "hasLabel": false,
        "continuationGroup": 7
      },
      {
        "x": 0.26625,
        "y": 0.61432,
        "width": 0.65371,
        "height": 0.04125,
        "hasLabel": false,
        "continuationGroup": 8
      },
      {
        "x": 0.32684,
        "y": 0.65519,
        "width": 0.59312,
        "height": 0.04513,
        "hasLabel": false,
        "continuationGroup": 9
      },
      {
        "x": 0.25497,
        "y": 0.70459,
        "width": 0.66499,
        "height": 0.04752,
        "hasLabel": false,
        "continuationGroup": 10
      },
      {
        "x": 0.26388,
        "y": 0.75023,
        "width": 0.65608,
        "height": 0.04564,
        "hasLabel": false,
        "continuationGroup": 11
      }
    ],
    "45": [
      {
        "x": 0.33511,
        "y": 0.60996,
        "width": 0.47134,
        "height": 0.028,
        "hasLabel": false,
        "continuationGroup": 1
      }
    ],
    "46": [
      {
        "x": 0.33511,
        "y": 0.60996,
        "width": 0.47134,
        "height": 0.028,
        "hasLabel": false,
        "continuationGroup": 1
      }
    ],
    "47": [
      {
        "x": 0.33511,
        "y": 0.60996,
        "width": 0.47134,
        "height": 0.028,
        "hasLabel": false,
        "continuationGroup": 1
      }
    ],
    "48": [
      {
        "x": 0.33511,
        "y": 0.60996,
        "width": 0.47134,
        "height": 0.028,
        "hasLabel": false,
        "continuationGroup": 1
      }
    ],
    "49": [
      {
        "x": 0.33511,
        "y": 0.60996,
        "width": 0.47134,
        "height": 0.028,
        "hasLabel": false,
        "continuationGroup": 1
      }
    ],
    "50": [
      {
        "x": 0.33511,
        "y": 0.60996,
        "width": 0.47134,
        "height": 0.028,
        "hasLabel": false,
        "continuationGroup": 1
      }
    ],
    "51": [
      {
        "x": 0.33511,
        "y": 0.60996,
        "width": 0.47134,
        "height": 0.028,
        "hasLabel": false,
        "continuationGroup": 1
      }
    ],
    "52": [
      {
        "x": 0.33511,
        "y": 0.60996,
        "width": 0.47134,
        "height": 0.028,
        "hasLabel": false,
        "continuationGroup": 1
      }
    ],
    "53": [
      {
        "x": 0.33511,
        "y": 0.60996,
        "width": 0.47134,
        "height": 0.028,
        "hasLabel": false,
        "continuationGroup": 1
      }
    ],
    "54": [
      {
        "x": 0.33511,
        "y": 0.60996,
        "width": 0.47134,
        "height": 0.028,
        "hasLabel": false,
        "continuationGroup": 1
      }
    ],
    "55": [
      {
        "x": 0.33511,
        "y": 0.60996,
        "width": 0.47134,
        "height": 0.028,
        "hasLabel": false,
        "continuationGroup": 1
      }
    ],
    "56": [
      {
        "x": 0.33511,
        "y": 0.60996,
        "width": 0.47134,
        "height": 0.028,
        "hasLabel": false,
        "continuationGroup": 1
      }
    ],
    "57": [],
    "58": [],
    "59": [],
    "60": []
  }
} as const;
