import type { GiftItem } from '@/app/(tabs)/gifts';

/** Товары из PDF «Товары для приложения Каталог» (дополнение к основному каталогу). */
export const PDF_CATALOG_GIFT_ITEMS: GiftItem[] = [
  {
    id: 'KFB1',
    title: 'Карточки для фотосессии беременных',
    sku: 'KFB1',
    link: 'https://www.wildberries.ru/catalog/66837949/detail.aspx',
    celebrations: ['Будущим мамам'],
  },
  {
    id: 'SO19',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO19',
    link: 'https://www.wildberries.ru/catalog/66852279/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO20',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO20',
    link: 'https://www.wildberries.ru/catalog/66852425/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO21',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO21',
    link: 'https://www.wildberries.ru/catalog/66853231/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO22',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO22',
    link: 'https://www.wildberries.ru/catalog/66855952/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO23',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO23',
    link: 'https://www.wildberries.ru/catalog/66856236/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO24',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO24',
    link: 'https://www.wildberries.ru/catalog/66856386/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO25',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO25',
    link: 'https://www.wildberries.ru/catalog/66856571/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO26',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO26',
    link: 'https://www.wildberries.ru/catalog/66865368/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO27',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO27',
    link: 'https://www.wildberries.ru/catalog/66865612/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO28',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO28',
    link: 'https://www.wildberries.ru/catalog/66869264/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'KDF2',
    title: 'Карточки для фотосессии малыша',
    sku: 'KDF2',
    link: 'https://www.wildberries.ru/catalog/66870220/detail.aspx',
    celebrations: ['Для новорождённых'],
  },
  {
    id: 'KDF3',
    title: 'Карточки для фотосессии малыша',
    sku: 'KDF3',
    link: 'https://www.wildberries.ru/catalog/66871090/detail.aspx',
    celebrations: ['Для новорождённых'],
  },
  {
    id: 'SO30',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO30',
    link: 'https://www.wildberries.ru/catalog/66968900/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO31',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO31',
    link: 'https://www.wildberries.ru/catalog/68985668/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO33',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO33',
    link: 'https://www.wildberries.ru/catalog/68986286/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO34',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO34',
    link: 'https://www.wildberries.ru/catalog/68986739/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO36',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO36',
    link: 'https://www.wildberries.ru/catalog/68988285/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO37',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO37',
    link: 'https://www.wildberries.ru/catalog/68988346/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO38',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO38',
    link: 'https://www.wildberries.ru/catalog/68988446/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO39',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO39',
    link: 'https://www.wildberries.ru/catalog/68988727/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO40',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO40',
    link: 'https://www.wildberries.ru/catalog/68989069/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO41',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO41',
    link: 'https://www.wildberries.ru/catalog/68989164/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO42',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO42',
    link: 'https://www.wildberries.ru/catalog/68989435/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO46',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO46',
    link: 'https://www.wildberries.ru/catalog/68991096/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO47',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO47',
    link: 'https://www.wildberries.ru/catalog/68991294/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO48',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO48',
    link: 'https://www.wildberries.ru/catalog/68991364/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO49',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO49',
    link: 'https://www.wildberries.ru/catalog/68991460/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO50',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO50',
    link: 'https://www.wildberries.ru/catalog/68991526/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO51',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO51',
    link: 'https://www.wildberries.ru/catalog/68991575/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO52',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO52',
    link: 'https://www.wildberries.ru/catalog/68992020/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'ROST1',
    title: 'Ростомер',
    sku: 'ROST1',
    link: 'https://www.wildberries.ru/catalog/84901445/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'ROST2',
    title: 'Ростомер',
    sku: 'ROST2',
    link: 'https://www.wildberries.ru/catalog/87360835/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'ROST3',
    title: 'Ростомер',
    sku: 'ROST3',
    link: 'https://www.wildberries.ru/catalog/87365958/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'ROST4',
    title: 'Ростомер',
    sku: 'ROST4',
    link: 'https://www.wildberries.ru/catalog/87365959/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'ROST5',
    title: 'Ростомер',
    sku: 'ROST5',
    link: 'https://www.wildberries.ru/catalog/87367573/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'ROST6',
    title: 'Ростомер',
    sku: 'ROST6',
    link: 'https://www.wildberries.ru/catalog/87367574/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'ROST7',
    title: 'Ростомер',
    sku: 'ROST7',
    link: 'https://www.wildberries.ru/catalog/87367575/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'ROST10',
    title: 'Ростомер',
    sku: 'ROST10',
    link: 'https://www.wildberries.ru/catalog/87371427/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'ROST9',
    title: 'Ростомер',
    sku: 'ROST9',
    link: 'https://www.wildberries.ru/catalog/87371428/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'ROST11',
    title: 'Ростомер',
    sku: 'ROST11',
    link: 'https://www.wildberries.ru/catalog/87381700/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'ROST12',
    title: 'Ростомер',
    sku: 'ROST12',
    link: 'https://www.wildberries.ru/catalog/87381701/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'ROST13',
    title: 'Ростомер',
    sku: 'ROST13',
    link: 'https://www.wildberries.ru/catalog/87381702/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'ROST14',
    title: 'Ростомер',
    sku: 'ROST14',
    link: 'https://www.wildberries.ru/catalog/87381703/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'ROST15',
    title: 'Ростомер',
    sku: 'ROST15',
    link: 'https://www.wildberries.ru/catalog/87386597/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'ROST17',
    title: 'Ростомер',
    sku: 'ROST17',
    link: 'https://www.wildberries.ru/catalog/87386599/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'ROST18',
    title: 'Ростомер',
    sku: 'ROST18',
    link: 'https://www.wildberries.ru/catalog/87386600/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'ROST19',
    title: 'Ростомер',
    sku: 'ROST19',
    link: 'https://www.wildberries.ru/catalog/87386601/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'ROST20',
    title: 'Ростомер',
    sku: 'ROST20',
    link: 'https://www.wildberries.ru/catalog/87389979/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'ROST22',
    title: 'Ростомер',
    sku: 'ROST22',
    link: 'https://www.wildberries.ru/catalog/87389981/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'ROST24',
    title: 'Ростомер',
    sku: 'ROST24',
    link: 'https://www.wildberries.ru/catalog/87389983/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'ROST25',
    title: 'Ростомер',
    sku: 'ROST25',
    link: 'https://www.wildberries.ru/catalog/87389984/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'POST2',
    title: 'Постер на стену в детскую комнату',
    sku: 'POST2',
    link: 'https://www.wildberries.ru/catalog/88625360/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'POST3',
    title: 'Постер на стену в детскую комнату',
    sku: 'POST3',
    link: 'https://www.wildberries.ru/catalog/88625361/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'POST4',
    title: 'Постер на стену в детскую комнату',
    sku: 'POST4',
    link: 'https://www.wildberries.ru/catalog/88625362/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'POST5',
    title: 'Постер на стену в детскую комнату',
    sku: 'POST5',
    link: 'https://www.wildberries.ru/catalog/88625363/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'POST6',
    title: 'Постер на стену в детскую комнату',
    sku: 'POST6',
    link: 'https://www.wildberries.ru/catalog/88625364/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'POST1',
    title: 'Постер на стену в детскую комнату',
    sku: 'POST1',
    link: 'https://www.wildberries.ru/catalog/88625366/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'POST9',
    title: 'Постер на стену в детскую комнату',
    sku: 'POST9',
    link: 'https://www.wildberries.ru/catalog/88625524/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'POST12',
    title: 'Постер на стену в детскую комнату',
    sku: 'POST12',
    link: 'https://www.wildberries.ru/catalog/88625952/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'POST14',
    title: 'Постер на стену в детскую комнату',
    sku: 'POST14',
    link: 'https://www.wildberries.ru/catalog/88625954/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'POST15',
    title: 'Постер на стену в детскую комнату',
    sku: 'POST15',
    link: 'https://www.wildberries.ru/catalog/88625955/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'POST16',
    title: 'Постер на стену в детскую комнату',
    sku: 'POST16',
    link: 'https://www.wildberries.ru/catalog/88625956/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'SO101',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO101',
    link: 'https://www.wildberries.ru/catalog/98804051/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO102',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO102',
    link: 'https://www.wildberries.ru/catalog/98804052/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO104',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO104',
    link: 'https://www.wildberries.ru/catalog/102487505/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO105',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO105',
    link: 'https://www.wildberries.ru/catalog/102693954/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO106',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO106',
    link: 'https://www.wildberries.ru/catalog/102693958/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO98',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO98',
    link: 'https://www.wildberries.ru/catalog/111635280/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO78',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO78',
    link: 'https://www.wildberries.ru/catalog/117619226/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'ROST100',
    title: 'Ростомер',
    sku: 'ROST100',
    link: 'https://www.wildberries.ru/catalog/117963320/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'ROST30',
    title: 'Ростомер',
    sku: 'ROST30',
    link: 'https://www.wildberries.ru/catalog/119181369/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'ROST31',
    title: 'Ростомер',
    sku: 'ROST31',
    link: 'https://www.wildberries.ru/catalog/119213117/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'ROST33',
    title: 'Ростомер',
    sku: 'ROST33',
    link: 'https://www.wildberries.ru/catalog/119216962/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'ROST34',
    title: 'Ростомер',
    sku: 'ROST34',
    link: 'https://www.wildberries.ru/catalog/119216963/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'SO110',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO110',
    link: 'https://www.wildberries.ru/catalog/123032772/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO112',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO112',
    link: 'https://www.wildberries.ru/catalog/123032773/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO109',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO109',
    link: 'https://www.wildberries.ru/catalog/123032775/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'ROST115',
    title: 'Ростомер',
    sku: 'ROST115',
    link: 'https://www.wildberries.ru/catalog/123048136/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'KDF3_2',
    title: 'Карточки для фотосессии малыша',
    sku: 'KDF3/2',
    link: 'https://www.wildberries.ru/catalog/134482946/detail.aspx',
    celebrations: ['Для новорождённых'],
  },
  {
    id: 'KDF3_3',
    title: 'Карточки для фотосессии малыша',
    sku: 'KDF3/3',
    link: 'https://www.wildberries.ru/catalog/136088106/detail.aspx',
    celebrations: ['Для новорождённых'],
  },
  {
    id: 'SO115',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO115',
    link: 'https://www.wildberries.ru/catalog/147790050/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO117',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO117',
    link: 'https://www.wildberries.ru/catalog/147790054/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'POST22',
    title: 'Постер на стену в детскую комнату',
    sku: 'POST22',
    link: 'https://www.wildberries.ru/catalog/152145138/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'POST23',
    title: 'Постер на стену в детскую комнату',
    sku: 'POST23',
    link: 'https://www.wildberries.ru/catalog/152145139/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'POST24',
    title: 'Постер на стену в детскую комнату',
    sku: 'POST24',
    link: 'https://www.wildberries.ru/catalog/152145140/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'POST25',
    title: 'Постер на стену в детскую комнату',
    sku: 'POST25',
    link: 'https://www.wildberries.ru/catalog/152145141/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'POST26',
    title: 'Постер на стену в детскую комнату',
    sku: 'POST26',
    link: 'https://www.wildberries.ru/catalog/152145142/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'SO123',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO123',
    link: 'https://www.wildberries.ru/catalog/152951113/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO122',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO122',
    link: 'https://www.wildberries.ru/catalog/152951114/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO121',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO121',
    link: 'https://www.wildberries.ru/catalog/152951115/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO120',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO120',
    link: 'https://www.wildberries.ru/catalog/152951116/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'MP1',
    title: 'Магнитный планер на холодильник',
    sku: 'MP1',
    link: 'https://www.wildberries.ru/catalog/152962711/detail.aspx',
    celebrations: ['Для семьи', 'В подарок'],
  },
  {
    id: 'MP2',
    title: 'Магнитный планер на холодильник',
    sku: 'MP2',
    link: 'https://www.wildberries.ru/catalog/152962712/detail.aspx',
    celebrations: ['Для семьи', 'В подарок'],
  },
  {
    id: 'MP3',
    title: 'Магнитный планер на холодильник',
    sku: 'MP3',
    link: 'https://www.wildberries.ru/catalog/152962713/detail.aspx',
    celebrations: ['Для семьи', 'В подарок'],
  },
  {
    id: 'MP4',
    title: 'Магнитный планер на холодильник',
    sku: 'MP4',
    link: 'https://www.wildberries.ru/catalog/152962714/detail.aspx',
    celebrations: ['Для семьи', 'В подарок'],
  },
  {
    id: 'MP5',
    title: 'Магнитный планер на холодильник',
    sku: 'MP5',
    link: 'https://www.wildberries.ru/catalog/152962715/detail.aspx',
    celebrations: ['Для семьи', 'В подарок'],
  },
  {
    id: 'MP6',
    title: 'Магнитный планер на холодильник',
    sku: 'MP6',
    link: 'https://www.wildberries.ru/catalog/152984309/detail.aspx',
    celebrations: ['Для семьи', 'В подарок'],
  },
  {
    id: 'MP7',
    title: 'Магнитный планер на холодильник',
    sku: 'MP7',
    link: 'https://www.wildberries.ru/catalog/152984310/detail.aspx',
    celebrations: ['Для семьи', 'В подарок'],
  },
  {
    id: 'MP10',
    title: 'Магнитный планер на холодильник',
    sku: 'MP10',
    link: 'https://www.wildberries.ru/catalog/152989748/detail.aspx',
    celebrations: ['Для семьи', 'В подарок'],
  },
  {
    id: 'MP8',
    title: 'Магнитный планер на холодильник',
    sku: 'MP8',
    link: 'https://www.wildberries.ru/catalog/152989749/detail.aspx',
    celebrations: ['Для семьи', 'В подарок'],
  },
  {
    id: 'MP9',
    title: 'Магнитный планер на холодильник',
    sku: 'MP9',
    link: 'https://www.wildberries.ru/catalog/152989750/detail.aspx',
    celebrations: ['Для семьи', 'В подарок'],
  },
  {
    id: 'MP23',
    title: 'Магнитный планер на холодильник',
    sku: 'MP23',
    link: 'https://www.wildberries.ru/catalog/153001308/detail.aspx',
    celebrations: ['Для семьи', 'В подарок'],
  },
  {
    id: 'MP25',
    title: 'Магнитный планер на холодильник',
    sku: 'MP25',
    link: 'https://www.wildberries.ru/catalog/153001310/detail.aspx',
    celebrations: ['Для семьи', 'В подарок'],
  },
  {
    id: 'SO126',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO126',
    link: 'https://www.wildberries.ru/catalog/167171046/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO127',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO127',
    link: 'https://www.wildberries.ru/catalog/167171048/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO128',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO128',
    link: 'https://www.wildberries.ru/catalog/167171049/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO132',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO132',
    link: 'https://www.wildberries.ru/catalog/167171050/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO129',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO129',
    link: 'https://www.wildberries.ru/catalog/167171053/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO130',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO130',
    link: 'https://www.wildberries.ru/catalog/167171054/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO131',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO131',
    link: 'https://www.wildberries.ru/catalog/167171064/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SO133',
    title: 'Обложка для свидетельства о рождении',
    sku: 'SO133',
    link: 'https://www.wildberries.ru/catalog/167171066/detail.aspx',
    celebrations: ['Для новорождённых', 'В подарок'],
  },
  {
    id: 'SVO2',
    title: 'Обложка для свидетельства о браке',
    sku: 'SVO2',
    link: 'https://www.wildberries.ru/catalog/177116016/detail.aspx',
    celebrations: ['Молодожёнам'],
  },
  {
    id: 'SVO3',
    title: 'Обложка для свидетельства о браке',
    sku: 'SVO3',
    link: 'https://www.wildberries.ru/catalog/177116329/detail.aspx',
    celebrations: ['Молодожёнам'],
  },
  {
    id: 'SVO5',
    title: 'Обложка для свидетельства о браке',
    sku: 'SVO5',
    link: 'https://www.wildberries.ru/catalog/177116330/detail.aspx',
    celebrations: ['Молодожёнам'],
  },
  {
    id: 'SVO8',
    title: 'Обложка для свидетельства о браке',
    sku: 'SVO8',
    link: 'https://www.wildberries.ru/catalog/177116331/detail.aspx',
    celebrations: ['Молодожёнам'],
  },
  {
    id: 'SVO9',
    title: 'Обложка для свидетельства о браке',
    sku: 'SVO9',
    link: 'https://www.wildberries.ru/catalog/177116332/detail.aspx',
    celebrations: ['Молодожёнам'],
  },
  {
    id: 'ROST166',
    title: 'Ростомер',
    sku: 'ROST166',
    link: 'https://www.wildberries.ru/catalog/197039017/detail.aspx',
    celebrations: ['Для детей'],
  },
  {
    id: 'SB1',
    title: 'Обложка для свидетельства о браке',
    sku: 'SB1',
    link: 'https://www.wildberries.ru/catalog/212225420/detail.aspx',
    celebrations: ['Молодожёнам'],
  },
  {
    id: 'SB2',
    title: 'Обложка для свидетельства о браке',
    sku: 'SB2',
    link: 'https://www.wildberries.ru/catalog/212230995/detail.aspx',
    celebrations: ['Молодожёнам'],
  },
  {
    id: 'SB3',
    title: 'Обложка для свидетельства о браке',
    sku: 'SB3',
    link: 'https://www.wildberries.ru/catalog/212231111/detail.aspx',
    celebrations: ['Молодожёнам'],
  },
  {
    id: 'SB4',
    title: 'Обложка для свидетельства о браке',
    sku: 'SB4',
    link: 'https://www.wildberries.ru/catalog/212232211/detail.aspx',
    celebrations: ['Молодожёнам'],
  },
  {
    id: 'SB5',
    title: 'Обложка для свидетельства о браке',
    sku: 'SB5',
    link: 'https://www.wildberries.ru/catalog/212232593/detail.aspx',
    celebrations: ['Молодожёнам'],
  },
  {
    id: 'KRR01',
    title: 'Магнитный планер на холодильник',
    sku: 'KRR01',
    link: 'https://www.wildberries.ru/catalog/265087616/detail.aspx',
    celebrations: ['Для семьи', 'В подарок'],
  },
  {
    id: 'DFA34',
    title: 'Фотоальбом дней рождений',
    sku: 'DFA34',
    link: 'https://www.wildberries.ru/catalog/68983865/detail.aspx',
    celebrations: ['В подарок', 'Для детей', 'День рождения'],
  },
  {
    id: 'DFA35',
    title: 'Фотоальбом дней рождений',
    sku: 'DFA35',
    link: 'https://www.wildberries.ru/catalog/68983950/detail.aspx',
    celebrations: ['В подарок', 'Для детей', 'День рождения'],
  },
  {
    id: 'DFA61',
    title: 'Фотоальбом Новый год',
    sku: 'DFA61',
    link: 'https://www.wildberries.ru/catalog/123041071/detail.aspx',
    celebrations: ['В подарок'],
  },
  {
    id: 'DFA62',
    title: 'Фотоальбом Новый год',
    sku: 'DFA62',
    link: 'https://www.wildberries.ru/catalog/138763357/detail.aspx',
    celebrations: ['В подарок'],
  },
  {
    id: 'GOST1',
    title: 'Книга пожеланий на день рождения',
    sku: 'GOST1',
    link: 'https://www.wildberries.ru/catalog/113473219/detail.aspx',
    celebrations: ['В подарок', 'День рождения'],
  },
  {
    id: 'GOST2',
    title: 'Книга пожеланий на свадьбу',
    sku: 'GOST2',
    link: 'https://www.wildberries.ru/catalog/113478132/detail.aspx',
    celebrations: ['Молодожёнам'],
  },
  {
    id: 'EDD1',
    title: 'Личный дневник для девочки А5',
    sku: 'EDD1',
    link: 'https://www.wildberries.ru/catalog/139359028/detail.aspx',
    celebrations: ['День рождения'],
  },
  {
    id: 'EDD2',
    title: 'Личный дневник для девочки А5',
    sku: 'EDD2',
    link: 'https://www.wildberries.ru/catalog/139359264/detail.aspx',
    celebrations: ['День рождения'],
  },
  {
    id: 'EDD3',
    title: 'Личный дневник для девочки А5',
    sku: 'EDD3',
    link: 'https://www.wildberries.ru/catalog/139359508/detail.aspx',
    celebrations: ['День рождения'],
  },
  {
    id: 'EDD4',
    title: 'Личный дневник для девочки А5',
    sku: 'EDD4',
    link: 'https://www.wildberries.ru/catalog/139359730/detail.aspx',
    celebrations: ['День рождения'],
  },
  {
    id: 'EDD5',
    title: 'Личный дневник для девочки А5',
    sku: 'EDD5',
    link: 'https://www.wildberries.ru/catalog/139360136/detail.aspx',
    celebrations: ['День рождения'],
  },
  {
    id: 'EDD6',
    title: 'Личный дневник для девочки А5',
    sku: 'EDD6',
    link: 'https://www.wildberries.ru/catalog/139360138/detail.aspx',
    celebrations: ['День рождения'],
  },
  {
    id: 'EDD7',
    title: 'Личный дневник для девочки А5',
    sku: 'EDD7',
    link: 'https://www.wildberries.ru/catalog/152682975/detail.aspx',
    celebrations: ['День рождения'],
  },
  {
    id: 'SA1',
    title: 'Фотоальбом свадебный 21х21 см',
    sku: 'SA1',
    link: 'https://www.wildberries.ru/catalog/212037885/detail.aspx',
    celebrations: ['Молодожёнам'],
  },
  {
    id: 'SA2',
    title: 'Фотоальбом свадебный 21х21 см',
    sku: 'SA2',
    link: 'https://www.wildberries.ru/catalog/212042532/detail.aspx',
    celebrations: ['Молодожёнам'],
  },
  {
    id: 'SA3',
    title: 'Фотоальбом свадебный 21х21 см',
    sku: 'SA3',
    link: 'https://www.wildberries.ru/catalog/212043356/detail.aspx',
    celebrations: ['Молодожёнам'],
  },
  {
    id: 'SA4',
    title: 'Фотоальбом свадебный 21х21 см',
    sku: 'SA4',
    link: 'https://www.wildberries.ru/catalog/212044677/detail.aspx',
    celebrations: ['Молодожёнам'],
  },
  {
    id: 'SA5',
    title: 'Фотоальбом свадебный 21х21 см',
    sku: 'SA5',
    link: 'https://www.wildberries.ru/catalog/212104557/detail.aspx',
    celebrations: ['Молодожёнам'],
  },
  {
    id: 'SDFA1',
    title: 'Фотоальбом семейный',
    sku: 'SDFA1',
    link: 'https://www.wildberries.ru/catalog/175404465/detail.aspx',
    celebrations: ['Для семьи'],
  },
  {
    id: 'SDFA2',
    title: 'Фотоальбом семейный',
    sku: 'SDFA2',
    link: 'https://www.wildberries.ru/catalog/175404826/detail.aspx',
    celebrations: ['Для семьи'],
  },
  {
    id: 'SDFA3',
    title: 'Фотоальбом семейный',
    sku: 'SDFA3',
    link: 'https://www.wildberries.ru/catalog/175405196/detail.aspx',
    celebrations: ['Для семьи'],
  },
  {
    id: 'SDFA4',
    title: 'Фотоальбом семейный',
    sku: 'SDFA4',
    link: 'https://www.wildberries.ru/catalog/175405296/detail.aspx',
    celebrations: ['Для семьи'],
  },
  {
    id: 'SDFA5',
    title: 'Фотоальбом семейный',
    sku: 'SDFA5',
    link: 'https://www.wildberries.ru/catalog/175163213/detail.aspx',
    celebrations: ['Для семьи'],
  },
  {
    id: 'SDFA6',
    title: 'Фотоальбом семейный',
    sku: 'SDFA6',
    link: 'https://www.wildberries.ru/catalog/175203190/detail.aspx',
    celebrations: ['Для семьи'],
  },
  {
    id: 'SDFA7',
    title: 'Фотоальбом семейный',
    sku: 'SDFA7',
    link: 'https://www.wildberries.ru/catalog/175405434/detail.aspx',
    celebrations: ['Для семьи'],
  },
];
