/** Auto-generated */
import type { ImageSourcePropType } from 'react-native';

export const KIDS_FIRST_PAGE_BY_ID: Record<string, ImageSourcePropType> = {
  'dfa_5': require('@/albums/kids/DFA5/first_page.png'),
  'dfa_7': require('@/albums/kids/DFA7/first_page.png'),
  'dfa_8': require('@/albums/kids/DFA8/first_page.png'),
  'dfa_9': require('@/albums/kids/DFA9/first_page.png'),
  'dfa_12': require('@/albums/kids/DFA12/first_page.png'),
  'dfa_15': require('@/albums/kids/DFA15/first_page.png'),
  'dfa_16': require('@/albums/kids/DFA16/first_page.png'),
  'dfa_19': require('@/albums/kids/DFA19/first_page.png'),
  'dfa_21': require('@/albums/kids/DFA21/first_page.png'),
  'dfa_22': require('@/albums/kids/DFA22/first_page.png'),
  'dfa_23': require('@/albums/kids/DFA23/first_page.png'),
  'dfa_24': require('@/albums/kids/DFA24/first_page.png'),
  'dfa_25': require('@/albums/kids/DFA25/first_page.png'),
  'dfa_26': require('@/albums/kids/DFA26/first_page.png'),
  'dfa_27': require('@/albums/kids/DFA27/first_page.png'),
  'dfa_28': require('@/albums/kids/DFA28/first_page.png'),
  'dfa_29': require('@/albums/kids/DFA29/first_page.png'),
  'dfa_30': require('@/albums/kids/DFA30/first_page.png'),
  'dfa_31': require('@/albums/kids/DFA31/first_page.png'),
  'dfa_43': require('@/albums/kids/DFA43/first_page.png'),
  'dfa_46': require('@/albums/kids/DFA46/first_page.png'),
  'dfa_47': require('@/albums/kids/DFA47/first_page.png'),
  'dfa_50': require('@/albums/kids/DFA50/first_page.png'),
  'dfa_52': require('@/albums/kids/DFA52/first_page.png'),
  'dfa_53': require('@/albums/kids/DFA53/first_page.png'),
  'dfa_59': require('@/albums/kids/DFA59/first_page.png'),
  'dfa_60': require('@/albums/kids/DFA60/first_page.png'),
  'dfa_71': require('@/albums/kids/DFA71/first_page.png'),
  'dfa_72': require('@/albums/kids/DFA72/first_page.png'),
  'dfa_74': require('@/albums/kids/DFA74/first_page.png'),
  'dfa_205': require('@/albums/kids/DFA205/first_page.png'),
  'dfa_206': require('@/albums/kids/DFA206/first_page.png'),
  'dfa_207': require('@/albums/kids/DFA207/first_page.png'),
  'dfa_208': require('@/albums/kids/DFA208/first_page.png'),
  'dfa_301': require('@/albums/kids/DFA301/first_page.png'),
  'dfa_302': require('@/albums/kids/DFA302/first_page.png'),
  'dfa_304': require('@/albums/kids/DFA304/first_page.png'),
  'dfa_305': require('@/albums/kids/DFA305/first_page.png'),
  'dfa_306': require('@/albums/kids/DFA306/first_page.png'),
  'dfa_307': require('@/albums/kids/DFA307/first_page.png'),
  'dfa_309': require('@/albums/kids/DFA309/first_page.png'),
};
