/**
 * Дизайны обложки для раздела «Первые годы малыша» (albums/kids).
 * Используется только first_page.png. Тип обложки выбирается при экспорте.
 */
import { COVER_BY_SKU } from '@/app/(tabs)/gifts';
export const KIDS_COVER_DESIGNS = [
  { id: 'dfa_5', image: COVER_BY_SKU.DFA5, sku: 'DFA5', title: 'DFA5' },
  { id: 'dfa_7', image: COVER_BY_SKU.DFA7, sku: 'DFA7', title: 'DFA7' },
  { id: 'dfa_8', image: COVER_BY_SKU.DFA8, sku: 'DFA8', title: 'DFA8' },
  { id: 'dfa_9', image: COVER_BY_SKU.DFA9, sku: 'DFA9', title: 'DFA9' },
  { id: 'dfa_12', image: require('@/assets/images/albums/blank_white.png'), sku: 'DFA12', title: 'DFA12' },
  { id: 'dfa_15', image: COVER_BY_SKU.DFA15, sku: 'DFA15', title: 'DFA15' },
  { id: 'dfa_16', image: COVER_BY_SKU.DFA16, sku: 'DFA16', title: 'DFA16' },
  { id: 'dfa_19', image: COVER_BY_SKU.DFA19, sku: 'DFA19', title: 'DFA19' },
  { id: 'dfa_21', image: COVER_BY_SKU.DFA21, sku: 'DFA21', title: 'DFA21' },
  { id: 'dfa_22', image: require('@/assets/images/albums/blank_white.png'), sku: 'DFA22', title: 'DFA22' },
  { id: 'dfa_23', image: COVER_BY_SKU.DFA23, sku: 'DFA23', title: 'DFA23' },
  { id: 'dfa_24', image: COVER_BY_SKU.DFA24, sku: 'DFA24', title: 'DFA24' },
  { id: 'dfa_25', image: COVER_BY_SKU.DFA25, sku: 'DFA25', title: 'DFA25' },
  { id: 'dfa_26', image: COVER_BY_SKU.DFA26, sku: 'DFA26', title: 'DFA26' },
  { id: 'dfa_27', image: COVER_BY_SKU.DFA27, sku: 'DFA27', title: 'DFA27' },
  { id: 'dfa_28', image: COVER_BY_SKU.DFA28, sku: 'DFA28', title: 'DFA28' },
  { id: 'dfa_29', image: COVER_BY_SKU.DFA29, sku: 'DFA29', title: 'DFA29' },
  { id: 'dfa_30', image: require('@/assets/images/albums/blank_white.png'), sku: 'DFA30', title: 'DFA30' },
  { id: 'dfa_31', image: COVER_BY_SKU.DFA31, sku: 'DFA31', title: 'DFA31' },
  { id: 'dfa_43', image: COVER_BY_SKU.DFA43, sku: 'DFA43', title: 'DFA43' },
  { id: 'dfa_46', image: COVER_BY_SKU.DFA46, sku: 'DFA46', title: 'DFA46' },
  { id: 'dfa_47', image: COVER_BY_SKU.DFA47, sku: 'DFA47', title: 'DFA47' },
  { id: 'dfa_50', image: COVER_BY_SKU.DFA50, sku: 'DFA50', title: 'DFA50' },
  { id: 'dfa_52', image: COVER_BY_SKU.DFA52, sku: 'DFA52', title: 'DFA52' },
  { id: 'dfa_53', image: COVER_BY_SKU.DFA53, sku: 'DFA53', title: 'DFA53' },
  { id: 'dfa_59', image: COVER_BY_SKU.DFA59, sku: 'DFA59', title: 'DFA59' },
  { id: 'dfa_60', image: COVER_BY_SKU.DFA60, sku: 'DFA60', title: 'DFA60' },
  { id: 'dfa_71', image: COVER_BY_SKU.DFA71, sku: 'DFA71', title: 'DFA71' },
  { id: 'dfa_72', image: COVER_BY_SKU.DFA72, sku: 'DFA72', title: 'DFA72' },
  { id: 'dfa_74', image: COVER_BY_SKU.DFA74, sku: 'DFA74', title: 'DFA74' },
  { id: 'dfa_205', image: COVER_BY_SKU.DFA205, sku: 'DFA205', title: 'DFA205' },
  { id: 'dfa_206', image: COVER_BY_SKU.DFA206, sku: 'DFA206', title: 'DFA206' },
  { id: 'dfa_207', image: COVER_BY_SKU.DFA207, sku: 'DFA207', title: 'DFA207' },
  { id: 'dfa_208', image: COVER_BY_SKU.DFA208, sku: 'DFA208', title: 'DFA208' },
  { id: 'dfa_301', image: COVER_BY_SKU.DFA301, sku: 'DFA301', title: 'DFA301' },
  { id: 'dfa_302', image: COVER_BY_SKU.DFA302, sku: 'DFA302', title: 'DFA302' },
  { id: 'dfa_304', image: COVER_BY_SKU.DFA304, sku: 'DFA304', title: 'DFA304' },
  { id: 'dfa_305', image: COVER_BY_SKU.DFA305, sku: 'DFA305', title: 'DFA305' },
  { id: 'dfa_306', image: COVER_BY_SKU.DFA306, sku: 'DFA306', title: 'DFA306' },
  { id: 'dfa_307', image: COVER_BY_SKU.DFA307, sku: 'DFA307', title: 'DFA307' },
  { id: 'dfa_309', image: COVER_BY_SKU.DFA309, sku: 'DFA309', title: 'DFA309' },
] as const;
