/**
 * Дизайны обложки для раздела «Первые годы малыша» (albums/kids).
 * Используется только first_page.png. Тип обложки выбирается при экспорте.
 */
const PLACEHOLDER_IMAGE = require('@/assets/images/albums/blank_white.png');
export const KIDS_COVER_DESIGNS = [
  { id: 'dfa_5', image: PLACEHOLDER_IMAGE, sku: 'DFA5', title: 'DFA5' },
  { id: 'dfa_7', image: PLACEHOLDER_IMAGE, sku: 'DFA7', title: 'DFA7' },
  { id: 'dfa_8', image: PLACEHOLDER_IMAGE, sku: 'DFA8', title: 'DFA8' },
  { id: 'dfa_9', image: PLACEHOLDER_IMAGE, sku: 'DFA9', title: 'DFA9' },
  { id: 'dfa_12', image: PLACEHOLDER_IMAGE, sku: 'DFA12', title: 'DFA12' },
  { id: 'dfa_15', image: PLACEHOLDER_IMAGE, sku: 'DFA15', title: 'DFA15' },
  { id: 'dfa_16', image: PLACEHOLDER_IMAGE, sku: 'DFA16', title: 'DFA16' },
  { id: 'dfa_19', image: PLACEHOLDER_IMAGE, sku: 'DFA19', title: 'DFA19' },
  { id: 'dfa_21', image: PLACEHOLDER_IMAGE, sku: 'DFA21', title: 'DFA21' },
  { id: 'dfa_22', image: PLACEHOLDER_IMAGE, sku: 'DFA22', title: 'DFA22' },
  { id: 'dfa_23', image: PLACEHOLDER_IMAGE, sku: 'DFA23', title: 'DFA23' },
  { id: 'dfa_24', image: PLACEHOLDER_IMAGE, sku: 'DFA24', title: 'DFA24' },
  { id: 'dfa_25', image: PLACEHOLDER_IMAGE, sku: 'DFA25', title: 'DFA25' },
  { id: 'dfa_26', image: PLACEHOLDER_IMAGE, sku: 'DFA26', title: 'DFA26' },
  { id: 'dfa_27', image: PLACEHOLDER_IMAGE, sku: 'DFA27', title: 'DFA27' },
  { id: 'dfa_28', image: PLACEHOLDER_IMAGE, sku: 'DFA28', title: 'DFA28' },
  { id: 'dfa_29', image: PLACEHOLDER_IMAGE, sku: 'DFA29', title: 'DFA29' },
  { id: 'dfa_30', image: PLACEHOLDER_IMAGE, sku: 'DFA30', title: 'DFA30' },
  { id: 'dfa_31', image: PLACEHOLDER_IMAGE, sku: 'DFA31', title: 'DFA31' },
  { id: 'dfa_43', image: PLACEHOLDER_IMAGE, sku: 'DFA43', title: 'DFA43' },
  { id: 'dfa_46', image: PLACEHOLDER_IMAGE, sku: 'DFA46', title: 'DFA46' },
  { id: 'dfa_47', image: PLACEHOLDER_IMAGE, sku: 'DFA47', title: 'DFA47' },
  { id: 'dfa_50', image: PLACEHOLDER_IMAGE, sku: 'DFA50', title: 'DFA50' },
  { id: 'dfa_52', image: PLACEHOLDER_IMAGE, sku: 'DFA52', title: 'DFA52' },
  { id: 'dfa_53', image: PLACEHOLDER_IMAGE, sku: 'DFA53', title: 'DFA53' },
  { id: 'dfa_59', image: PLACEHOLDER_IMAGE, sku: 'DFA59', title: 'DFA59' },
  { id: 'dfa_60', image: PLACEHOLDER_IMAGE, sku: 'DFA60', title: 'DFA60' },
  { id: 'dfa_71', image: PLACEHOLDER_IMAGE, sku: 'DFA71', title: 'DFA71' },
  { id: 'dfa_72', image: PLACEHOLDER_IMAGE, sku: 'DFA72', title: 'DFA72' },
  { id: 'dfa_74', image: PLACEHOLDER_IMAGE, sku: 'DFA74', title: 'DFA74' },
  { id: 'dfa_205', image: PLACEHOLDER_IMAGE, sku: 'DFA205', title: 'DFA205' },
  { id: 'dfa_206', image: PLACEHOLDER_IMAGE, sku: 'DFA206', title: 'DFA206' },
  { id: 'dfa_207', image: PLACEHOLDER_IMAGE, sku: 'DFA207', title: 'DFA207' },
  { id: 'dfa_208', image: PLACEHOLDER_IMAGE, sku: 'DFA208', title: 'DFA208' },
  { id: 'dfa_301', image: PLACEHOLDER_IMAGE, sku: 'DFA301', title: 'DFA301' },
  { id: 'dfa_302', image: PLACEHOLDER_IMAGE, sku: 'DFA302', title: 'DFA302' },
  { id: 'dfa_304', image: PLACEHOLDER_IMAGE, sku: 'DFA304', title: 'DFA304' },
  { id: 'dfa_305', image: PLACEHOLDER_IMAGE, sku: 'DFA305', title: 'DFA305' },
  { id: 'dfa_306', image: PLACEHOLDER_IMAGE, sku: 'DFA306', title: 'DFA306' },
  { id: 'dfa_307', image: PLACEHOLDER_IMAGE, sku: 'DFA307', title: 'DFA307' },
  { id: 'dfa_309', image: PLACEHOLDER_IMAGE, sku: 'DFA309', title: 'DFA309' },
] as const;
